# -*- coding: utf-8 -*-
import io
import zipfile
import base64
import csv
from odoo import models, fields, api

class BaseAutomation(models.Model):
    _inherit = 'base.automation'

    is_studio_ce = fields.Boolean(string='Created by Studio CE', default=False)

class IrUiMenu(models.Model):
    _inherit = 'ir.ui.menu'

    is_studio_ce = fields.Boolean(string='Created by Studio CE', default=False)

class StudioCeExport(models.TransientModel):
    _name = 'studio.ce.export'
    _description = 'Studio CE Customization Export Engine'

    name = fields.Char(string='File Name', default='studio_ce_customizations.zip')
    zip_file = fields.Binary(string='Zip File', readonly=True)

    def action_export_zip(self):
        # 1. Gather custom models
        custom_models = self.env['ir.model'].search([('is_studio_ce', '=', True)])
        custom_model_names = custom_models.mapped('model')

        # 2. Gather custom fields
        custom_fields = self.env['ir.model.fields'].search([('is_studio_ce', '=', True)])

        # 3. Gather custom views
        custom_views = self.env['ir.ui.view'].search([('is_studio_ce', '=', True)])

        # 4. Gather custom menus
        custom_menus = self.env['ir.ui.menu'].search([('is_studio_ce', '=', True)])

        # 5. Gather custom automations
        custom_automations = self.env['base.automation'].search([('is_studio_ce', '=', True)])

        # 6. Gather window actions for custom models
        custom_actions = self.env['ir.actions.act_window'].search([('res_model', 'in', custom_model_names)])

        # 7. Gather custom security ACLs for custom models
        custom_acls = self.env['ir.model.access'].search([('model_id.model', 'in', custom_model_names)])

        # 8. Gather custom record rules
        custom_rules = self.env['ir.rule'].search([('is_studio_ce', '=', True)])

        # 9. Gather custom approvals
        custom_approvals = self.env['studio.ce.approval'].search([('active', '=', True)])

        # Create zip in memory
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            # Write manifest
            manifest = f"""# -*- coding: utf-8 -*-
{{
    'name': 'Studio CE Customizations',
    'version': '1.0',
    'summary': 'Exported customizations from Studio CE',
    'depends': ['base', 'web', 'base_automation', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/custom_rules.xml',
        'views/custom_views.xml',
        'views/custom_menus.xml',
        'data/custom_automations.xml',
        'data/custom_approvals.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}}
"""
            zip_file.writestr('__manifest__.py', manifest)
            zip_file.writestr('__init__.py', "from . import models\n")
            zip_file.writestr('models/__init__.py', "from . import custom_models\n")

            # Generate models/custom_models.py
            models_code = ["# -*- coding: utf-8 -*-\nfrom odoo import models, fields\n"]
            
            # First, define brand new custom models
            for model in custom_models:
                class_name = ''.join([x.capitalize() for x in model.model.split('.')])
                models_code.append(f"\nclass {class_name}(models.Model):")
                models_code.append(f"    _name = '{model.model}'")
                models_code.append(f"    _description = '{model.name}'\n")

            # Differentiate fields: custom fields on custom models vs custom fields on inherited models
            grouped_fields = {}
            for field in custom_fields:
                grouped_fields.setdefault(field.model, []).append(field)

            for model_name, fields_list in grouped_fields.items():
                if model_name not in custom_model_names:
                    # Inherited model
                    class_name = ''.join([x.capitalize() for x in model_name.split('.')])
                    models_code.append(f"\nclass {class_name}(models.Model):")
                    models_code.append(f"    _inherit = '{model_name}'\n")
                
                # Render field declarations
                for f in fields_list:
                    # Skip autogenerated x_name Char field for custom models as it's typically default
                    if model_name in custom_model_names and f.name == 'x_name':
                        models_code.append("    x_name = fields.Char(string='Name', required=True)")
                        continue

                    f_type = f.ttype
                    kwargs = [f"string='{f.field_description}'"]
                    if f.required:
                        kwargs.append("required=True")
                    if f.readonly:
                        kwargs.append("readonly=True")
                    
                    if f_type == 'char':
                        models_code.append(f"    {f.name} = fields.Char({', '.join(kwargs)})")
                    elif f_type == 'text':
                        models_code.append(f"    {f.name} = fields.Text({', '.join(kwargs)})")
                    elif f_type == 'integer':
                        models_code.append(f"    {f.name} = fields.Integer({', '.join(kwargs)})")
                    elif f_type == 'float':
                        models_code.append(f"    {f.name} = fields.Float({', '.join(kwargs)})")
                    elif f_type == 'boolean':
                        models_code.append(f"    {f.name} = fields.Boolean({', '.join(kwargs)})")
                    elif f_type == 'selection':
                        selection_values = f.selection_ids or [('draft', 'Draft')]
                        models_code.append(f"    {f.name} = fields.Selection({selection_values}, {', '.join(kwargs)})")
                    elif f_type == 'many2one':
                        kwargs.insert(0, f"'{f.relation}'")
                        models_code.append(f"    {f.name} = fields.Many2one({', '.join(kwargs)})")
            
            zip_file.writestr('models/custom_models.py', '\n'.join(models_code))

            # Generate views/custom_views.xml
            views_xml = ['<?xml version="1.0" encoding="utf-8"?>\n<odoo>']
            
            # Export window actions
            for action in custom_actions:
                views_xml.append(f"""    <record id="action_custom_{action.id}" model="ir.actions.act_window">
        <field name="name">{action.name}</field>
        <field name="res_model">{action.res_model}</field>
        <field name="view_mode">{action.view_mode}</field>
        <field name="target">{action.target}</field>
    </record>""")

            # Export inherited or custom views
            for view in custom_views:
                inherit_str = ""
                if view.inherit_id:
                    xml_id = view.inherit_id.get_metadata()[0].get('xmlid') or f"view_{view.inherit_id.id}"
                    inherit_str = f'\n        <field name="inherit_id" ref="{xml_id}"/>'
                
                views_xml.append(f"""    <record id="view_custom_{view.id}" model="ir.ui.view">
        <field name="name">{view.name}</field>
        <field name="model">{view.model}</field>{inherit_str}
        <field name="arch" type="xml">
{view.arch}
        </field>
    </record>""")
            views_xml.append('</odoo>')
            zip_file.writestr('views/custom_views.xml', '\n'.join(views_xml))

            # Generate views/custom_menus.xml
            menus_xml = ['<?xml version="1.0" encoding="utf-8"?>\n<odoo>']
            for menu in custom_menus:
                parent_ref = ""
                if menu.parent_id:
                    parent_xml_id = menu.parent_id.get_metadata()[0].get('xmlid') or f"menu_custom_{menu.parent_id.id}"
                    parent_ref = f' parent="{parent_xml_id}"'
                
                action_ref = ""
                if menu.action:
                    action_model, action_id = menu.action._name, menu.action.id
                    if action_model == 'ir.actions.act_window':
                        action_ref = f' action="action_custom_{action_id}"'
                
                menus_xml.append(f'    <menuitem id="menu_custom_{menu.id}" name="{menu.name}"{parent_ref}{action_ref} sequence="{menu.sequence}"/>')
            menus_xml.append('</odoo>')
            zip_file.writestr('views/custom_menus.xml', '\n'.join(menus_xml))

            # Generate data/custom_automations.xml
            automations_xml = ['<?xml version="1.0" encoding="utf-8"?>\n<odoo>\n    <data noupdate="1">']
            for auto in custom_automations:
                automations_xml.append(f"""        <record id="automation_custom_{auto.id}" model="base.automation">
            <field name="name">{auto.name}</field>
            <field name="model_id" ref="base.model_{auto.model_id.model.replace('.', '_')}"/>
            <field name="trigger">{auto.trigger}</field>
            <field name="active" eval="True"/>
        </record>""")
            automations_xml.append('    </data>\n</odoo>')
            zip_file.writestr('data/custom_automations.xml', '\n'.join(automations_xml))

            # Generate data/custom_approvals.xml
            approvals_xml = ['<?xml version="1.0" encoding="utf-8"?>\n<odoo>\n    <data noupdate="1">']
            for approval in custom_approvals:
                approvals_xml.append(f"""        <record id="approval_custom_{approval.id}" model="studio.ce.approval">
            <field name="name">{approval.name}</field>
            <field name="model_id" ref="base.model_{approval.model_id.model.replace('.', '_')}"/>
            <field name="button_name">{approval.button_name}</field>
            <field name="required_domain">{approval.required_domain}</field>
            <field name="active" eval="True"/>
        </record>""")
                for step in approval.rule_ids:
                    approvals_xml.append(f"""        <record id="approval_step_custom_{step.id}" model="studio.ce.approval.rule">
            <field name="approval_id" ref="approval_custom_{approval.id}"/>
            <field name="name">{step.name}</field>
            <field name="sequence">{step.sequence}</field>
            <field name="exclusive" eval="{step.exclusive}"/>
        </record>""")
            approvals_xml.append('    </data>\n</odoo>')
            zip_file.writestr('data/custom_approvals.xml', '\n'.join(approvals_xml))

            # Generate security/custom_rules.xml
            rules_xml = ['<?xml version="1.0" encoding="utf-8"?>\n<odoo>\n    <data noupdate="1">']
            for rule in custom_rules:
                rules_xml.append(f"""        <record id="rule_custom_{rule.id}" model="ir.rule">
            <field name="name">{rule.name}</field>
            <field name="model_id" ref="base.model_{rule.model_id.model.replace('.', '_')}"/>
            <field name="domain_force">{rule.domain_force}</field>
            <field name="perm_read" eval="{rule.perm_read}"/>
            <field name="perm_write" eval="{rule.perm_write}"/>
            <field name="perm_create" eval="{rule.perm_create}"/>
            <field name="perm_unlink" eval="{rule.perm_unlink}"/>
            <field name="active" eval="{rule.active}"/>
        </record>""")
            rules_xml.append('    </data>\n</odoo>')
            zip_file.writestr('security/custom_rules.xml', '\n'.join(rules_xml))

            # Generate security/ir.model.access.csv
            acl_csv_io = io.StringIO()
            writer = csv.writer(acl_csv_io)
            writer.writerow(['id', 'name', 'model_id:id', 'group_id:id', 'perm_read', 'perm_write', 'perm_create', 'perm_unlink'])
            for acl in custom_acls:
                model_xml_id = f"model_{acl.model_id.model.replace('.', '_')}"
                group_xml_id = ""
                if acl.group_id:
                    group_xml_id = acl.group_id.get_metadata()[0].get('xmlid') or f"base.group_{acl.group_id.id}"
                
                writer.writerow([
                    f"access_custom_{acl.id}",
                    acl.name,
                    model_xml_id,
                    group_xml_id,
                    int(acl.perm_read),
                    int(acl.perm_write),
                    int(acl.perm_create),
                    int(acl.perm_unlink)
                ])
            zip_file.writestr('security/ir.model.access.csv', acl_csv_io.getvalue())

        zip_buffer.seek(0)
        self.zip_file = base64.b64encode(zip_buffer.read())
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/?model=studio.ce.export&id={self.id}&field=zip_file&download=true&filename={self.name}',
            'target': 'self',
        }

